puts "The Students of Villians Academy"
puts "--------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Rached"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Jofferey Baratheon"
puts "Norman Bates"